[project]
name = "scarcity"
requirements = []

[contracts.citycoin-token-trait]
path = "contracts/traits/citycoin-token-trait.clar"
depends_on = []

[contracts.mint-test-token-one]
path = "contracts/testing/mint-test-token-one.clar"
depends_on = []

[contracts.mint-test-token-two]
path = "contracts/testing/mint-test-token-two.clar"
depends_on = []

[contracts.scarcity-token]
path = "contracts/scarcity-token.clar"
depends_on = ["mint-test-token-one", "mint-test-token-two", "citycoin-token-trait"]

